name: Update Discord Data

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Read Discord
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
        run: python scraper/main.py
